/*
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose 
 * values do not exceed four million, find the sum of the even-valued terms. 
 */

public class Solution {
	
	static long getSum() {
		int max = 4000000;
		long sum = 0;
		int first = 0;
		int second = 1;
		
		while(true) {
			int third = first + second;
			
			if(third > max)
				break;
			
			if(third % 2 == 0)
				sum += third;
			
			first = second;
			second = third;
		}
		
		return sum;
	}
	
	public static void main(String[] a) {
		System.out.println(getSum());
	}
}
